name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 或你希望部署的分支

  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == 'EchoXigua'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run deploy:frontend  --base=HEAD~1 --head=HEAD # 替换为你的构建命令，例如 `nx build`

      - name: Make deploy script executable
        run: chmod +x ./scripts/deploy-github.sh

      - name: Prepare deployment
        run: |
          # 运行部署脚本，将构建输出移动到 gh-pages 目录
          ./scripts/deploy-github.sh

      - name: List files in the current directory
        run: ls -al

      - name: List files in the `gh-pages` directory
        run: ls -al ./gh-pages

      - name: set up git user
        run: |
          git config --global user.email "643589668@qq.com"
          git config --global user.name "xg-ci"
          git remote set-url origin https://x-access-token:${{ secrets.XG_CI_TOKEN }}@github.com/EchoXigua/xg-monorepo.git

      # - name: release version
      #   run: pnpm exec nx release --skip-publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.XG_CI_TOKEN }}

      - name: git push & git tag
        run: |
          echo "Some changes" >> test.txt
          git add . 
          git commit -m 'test token perm [skip ci]'
          git push origin main
      #    git push origin main --tags
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages # 替换为你的构建输出目录
          publish_branch: gh-pages # 发布到 gh-pages 分支
